---
name: 'Setup node'

inputs:
  version:
    description: 'Node version to use'
    required: false
    type: string
    default: '20'
  npm_token:
    description: 'NPM Token'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Authenticate npm 🔑
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm_token }}" > ~/.npmrc
    - name: Cache Dependencies ⌛️
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package*.json') }}-${{ hashFiles('.github/actions/setup-node/action.yml') }}-node-${{ inputs.version }}
    - name: Setup Node ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version }}
        cache: npm
    - name: Install dependencies 📥
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
