---
name: Dispatch slash commands

on:
  issue_comment:
    types:
      - created

permissions:
  pull-requests: write
  issues: write
  checks: read

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch 🚀
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          config: >
            [
              {
                "command": "create-rc",
                "permission": "write",
                "issue_type": "pull-request"
              },
              {
                "command": "help",
                "permission": "none",
                "issue_type": "pull-request",
                "event_type_suffix": "-pr-command"
              }
            ]
